config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'advisees#index', as: :authenticated_root
  end

  root 'home#index'

  get "/auth/:provider/callback" => 'identities#create'

  resources :advisees do
    resources :graduation_plans, only: [:index, :new, :create]
  end

  resources :graduation_plans, only: [:show, :destroy]

  resources :meetings, only: [:show, :edit, :update, :destroy] do
    resources :meeting_summaries, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :all_meetings, only: [:index]
      resources :google_calendars, only: [:index]
      resources :microsoft_calendars, only: [:index]
      resources :notes, only: [:update, :destroy]
      resources :search_advisees, only: [:index]
      resources :upcoming_meetings, only: [:index]
      resources :courses, only: [:update, :destroy]

      resources :advisees, only: [] do
        resources :advisee_notes, only: [:index, :create]
        resources :meetings, only: [:index, :create]
      end

      resources :meetings, only: [:update, :destroy] do
        resources :meeting_notes, only: [:index, :create]
        resources :google_calendars, only: [:create]
        resources :microsoft_calendars, only: [:create]
      end

      resources :graduation_plans, only: [:update] do
        resources :semesters, only: [:index]
      end

      resources :semesters, only: [] do
        resources :courses, only: [:create]
      end
    end
  end
end

app/models/advisee.rb
require 'digest/md5'

class Advisee < ActiveRecord::Base
  include PgSearch
  mount_uploader :photo, AdviseePhotoUploader

  belongs_to :user
  has_many :notes, as: :noteable, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :graduation_plans, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
                              message: 'That is not a valid email address' }
  validates :graduation_semester, presence: true,
                                  inclusion: { in: Semesters.all }
  validates :graduation_year, numericality: { only_integer: true,
                                              greater_than: 1990,
                                              less_than: 9999 }

  pg_search_scope :search_advisees,
                  against: [:first_name, :last_name, :email],
                  using: {
                    tsearch: { prefix: true }
                  }
  scope :search, -> (query) { search_advisees(query) if query.present? }

  def self.all_for(user)
    Advisee.where(user: user)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def photo_url
    if photo.to_s == ""
      "https://www.gravatar.com/avatar/#{email_hash}"
    else
      photo.to_s
    end
  end

  def as_json(options = {})
    h = super(options)
    h[:photo_url] = photo_url
    h
  end

  private

  def email_hash
    Digest::MD5.hexdigest(email)
  end
end

app/controllers/advisees_controller.rb
class AdviseesController < ApplicationController
  before_filter :authenticate_user!
  before_filter only: [:show, :edit, :update, :destroy] do
    check_permissions(Advisee.find(params[:id]))
  end

  def index
    @advisees = Advisee.all_for(current_user)
  end

  def show
    @advisee = Advisee.find(params[:id])
    @notes = @advisee.notes.order(updated_at: :desc)
  end

  def new
    @advisee = Advisee.new
    @semesters = Semesters.all_for_select
  end

  def create
    @advisee = Advisee.new(advisee_params)
    @advisee.user = current_user

    if @advisee.save
      flash[:success] = 'Advisee added successfully'
      redirect_to advisee_path(@advisee)
    else
      flash[:alert] = 'There was a problem creating that advisee'
      @errors = @advisee.errors.full_messages
      @semesters = Semesters.all_for_select

      render 'advisees/new'
    end
  end

  def edit
    @advisee = Advisee.find(params[:id])
    @semesters = Semesters.all_for_select
  end

  def update
    @advisee = Advisee.find(params[:id])

    if @advisee.update(advisee_params)
      flash[:success] = 'Advisee info updated!'
      redirect_to advisee_path(@advisee)
    else
      flash[:alert] = 'There were problems updating the advisee'
      @errors = @advisee.errors.full_messages
      @semesters = Semesters.all_for_select

      render 'advisees/edit'
    end
  end

  def destroy
    Advisee.destroy(params[:id])
    flash[:success] = 'Advisee deleted successfully!'

    redirect_to advisees_path
  end

  private

  def advisee_params
    params.require(:advisee).permit(:first_name,
                                    :last_name,
                                    :email,
                                    :graduation_semester,
                                    :graduation_year,
                                    :photo)
  end
end

app/views/advisees/_advisee.html.erb
<%= link_to advisee_path(advisee) do %>
  <div class="advisee valign-wrapper">
    <h2 class="valign"><%= advisee.full_name %></h2>
    <h3 class="valign">
      <%= advisee.graduation_semester %>
      <%= advisee.graduation_year %>
    </h3>
  </div>
<% end %>

app/views/advisees/_delete_modal.html.erb
<div id="delete-advisee-modal" class="modal">
  <div class="modal-content">
    <h4>Delete Advisee?</h4>
    <p>
      Are you sure you want to delete <%= advisee.full_name %> and all of their
      information?
    </p>
    <p>
      <b>Warning:</b> This cannot be undone.
    </p>
  </div>
  <div class="modal-footer">
    <%= button_to 'Yes, Delete Advisee',
                  advisee_path(advisee),
                  method: 'delete',
                  class: 'btn danger modal-action modal-close' %>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">
      Cancel
    </a>
  </div>
</div>

app/views/advisees/_details.html.erb
<div class="row">
  <div class="col s12 m3 photo">
    <img src="<%= @advisee.photo_url %>"
         alt="<%= "Photo of #{@advisee.full_name}" %>"
         class="responsive-img circle" />
  </div>
  <div class="col s12 m9">
    <h2 class="advisee-name">
      <%= link_to @advisee.full_name, advisee_path(@advisee) %>
      <small>(<%= mail_to @advisee.email %>)</small>
    </h2>
    <h3><%= @advisee.graduation_semester %> <%= @advisee.graduation_year %></h3>
  </div>
</div>

app/views/advisees/_form.html.erb
<%= render partial: 'layouts/errors' %>

<%= form_for @advisee do |f| %>
  <div class="input-field">
    <%= f.label :first_name, 'First Name' %>
    <%= f.text_field :first_name %>
  </div>

  <div class="input-field">
    <%= f.label :last_name, 'Last Name' %>
    <%= f.text_field :last_name %>
  </div>

  <div class="input-field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="input-field">
    <%= f.select :graduation_semester, @semesters %>
    <%= f.label :graduation_semester, 'Graduation Semester' %>
  </div>

  <div class="input-field">
    <%= f.label :graduation_year, 'Graduation Year' %>
    <%= f.number_field :graduation_year, min: 1990, max: 10000 %>
  </div>

  <div class="file-field input-field">
    <div class="btn primary">
      <span>Photo</span>
      <%= f.file_field :photo, accept: 'image/png,image/gif,image/jpeg' %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text">
    </div>
  </div>

  <div class="input-field">
    <%= f.submit 'Save Advisee', class: 'btn primary' %>
  </div>
<% end %>

app/views/advisees/edit.html.erb
<div class="container">
  <h2>Edit Advisee Information</h2>
  <%= render partial: 'advisees/form' %>
</div>

app/views/advisees/index.html.erb
<div class="container">
</div>

<div class="row">
  <div class="col s12 m8">
    <div class="row">
      <div class="col s12 m8">
        <h1>Advisees</h1>
      </div>
      <div class="col s12 m4">
        <%= link_to new_advisee_path, class: 'btn primary add-advisee' do %>
           <i class="material-icons left">add</i>
          Add Advisee
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div id="advisee-search">
          <div class="advisees">
            <% @advisees.each do |advisee| %>
              <%= render partial: 'advisees/advisee', object: advisee %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <div id="upcoming-meetings">
    </div>
  </div>
</div>

app/views/advisees/new.html.erb
<div class="container">
  <h2>Add an Advisee</h2>
  <%= render partial: 'advisees/form' %>
</div>

app/views/advisees/show.html.erb
<div class="container advisee-details">
  <div id="advisee-data" data-id="<%= @advisee.id %>" />

  <%= render partial: 'advisees/details' %>

  <%= link_to advisee_graduation_plans_path(@advisee), class: 'btn primary' do %>
    <i class="material-icons left">view_list</i>
    Graduation Plans
  <% end %>

  <%= link_to edit_advisee_path(@advisee), class: 'btn primary' do %>
    <i class="material-icons left">mode_edit</i>
    Edit Advisee
  <% end %>

  <button data-target="delete-advisee-modal" class="btn danger modal-trigger">
    <i class="material-icons left">delete</i>
    Delete Advisee
  </button>
  <%= render partial: 'advisees/delete_modal', locals: { advisee: @advisee } %>

  <div class="row notes-and-meetings">
    <div class="col s12 m6">
      <h5 class="title">Notes</h5>
      <div id="advisee-notes">
        <% if @notes.count == 0 %>
          <p>
            There are no notes for this advisee.
          </p>
          <button class="btn primary">
            <i class="material-icons left">add</i> Add Note
          </button>
        <% end %>

        <% @notes.each do |note| %>
          <div class="note">
            <p>
              <%= note.body %>
            </p>
            <h4><%= note.updated_at %></h4>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col s12 m6">
      <h5 class="title">Meetings</h5>
      <div id="advisee-meetings">
      </div>
    </div>
  </div>
</div>