config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'advisees#index', as: :authenticated_root
  end

  root 'home#index'

  get "/auth/:provider/callback" => 'identities#create'

  resources :advisees do
    resources :graduation_plans, only: [:index, :new, :create]
  end

  resources :graduation_plans, only: [:show, :destroy]

  resources :meetings, only: [:show, :edit, :update, :destroy] do
    resources :meeting_summaries, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :all_meetings, only: [:index]
      resources :google_calendars, only: [:index]
      resources :microsoft_calendars, only: [:index]
      resources :notes, only: [:update, :destroy]
      resources :search_advisees, only: [:index]
      resources :upcoming_meetings, only: [:index]
      resources :courses, only: [:update, :destroy]

      resources :advisees, only: [] do
        resources :advisee_notes, only: [:index, :create]
        resources :meetings, only: [:index, :create]
      end

      resources :meetings, only: [:update, :destroy] do
        resources :meeting_notes, only: [:index, :create]
        resources :google_calendars, only: [:create]
        resources :microsoft_calendars, only: [:create]
      end

      resources :graduation_plans, only: [:update] do
        resources :semesters, only: [:index]
      end

      resources :semesters, only: [] do
        resources :courses, only: [:create]
      end
    end
  end
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_writer :duration

  belongs_to :advisee
  belongs_to :user
  has_many :notes, as: :noteable, dependent: :destroy

  validates :start_time, presence: true, timeliness: true
  validates :end_time, presence: true, timeliness: true
  validates :advisee, presence: true

  def self.new_from_duration(params)
    meeting = Meeting.new(params)

    if params[:duration] && params[:duration] != '' && meeting.start_time
      meeting.end_time = meeting.start_time + params[:duration].to_i.minutes
    end

    meeting
  end

  def self.update_from_duration(meeting, params)
    if params[:start_time] && params[:start_time] != ''
      params[:end_time] = Time.zone.parse(params[:start_time]) +
      params[:duration].to_i.minutes
    end

    meeting.update(params)
  end

  def self.upcomming_for_user(user)
    where(user: user)
      .where('start_time > ?', Time.zone.now - 1.hour)
      .order(start_time: :desc)
      .limit(5)
  end

  def self.format_for_upcoming(meetings)
    meetings.map do |meeting|
      advisee = meeting.advisee

      {
        id: meeting.id,
        description: meeting.description,
        start_time: meeting.start_time,
        end_time: meeting.end_time,
        duration: meeting.duration,
        advisee: {
          id: advisee.id,
          full_name: advisee.full_name,
          first_name: advisee.first_name,
          last_name: advisee.last_name
        }
      }
    end
  end

  def duration
    if !start_time || !end_time
      0
    else
      (end_time - start_time) / 60.to_f
    end
  end

  def formatted_date_only
    start_time.strftime('%B %d, %Y')
  end

  def formatted_time
    "#{start_time.strftime('%b %d, %Y from%l:%M %p')} to "\
                           "#{end_time.strftime('%l:%M %p')}"
  end

  def formatted_start_time
    start_time.strftime('%b %d, %Y - %l:%M %p')
  end

  def as_json(options = {})
    m = super(options)
    m[:duration] = duration
    m
  end
end

app/controllers/api/v1/meetings_controller.rb
class Api::V1::MeetingsController < ApiController
  include MeetingParams

  before_filter :authenticate_user!
  before_filter only: [:index, :create] do
    check_permissions(Advisee.find(params[:advisee_id]))
  end
  before_filter only: [:update, :destroy] do
    check_permissions(Meeting.find(params[:id]))
  end

  def index
    advisee = Advisee.find(params[:advisee_id])
    meetings = advisee.meetings.order(start_time: :desc)

    render json: { meetings: meetings }, status: :ok
  end

  def create
    meeting = Meeting.new_from_duration(meeting_params)
    meeting.advisee_id = params[:advisee_id]
    meeting.user = current_user

    if meeting.save
      message = 'Meeting created!'

      render json: { message: message, meeting: meeting }, status: :ok
    else
      message = 'There were problems creating that meeting'
      errors = meeting.errors.full_messages

      render json: { message: message, errors: errors }, status: :bad_request
    end
  end

  def update
    meeting = Meeting.find(params[:id])

    if meeting.update(meeting_params)
      message = 'Meeting updated!'

      render json: { message: message, meeting: meeting }, status: :ok
    else
      message = 'There were problems updating that meeting'
      errors = meeting.errors.full_messages

      render json: { message: message, errors: errors }, status: :bad_request
    end
  end

  def destroy
    Meeting.destroy(params[:id])

    render json: { message: 'Meeting deleted!' }, status: :ok
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  include MeetingParams

  before_filter :authenticate_user!
  before_filter only: [:show, :edit, :update, :destroy] do
    check_permissions(Meeting.find(params[:id]))
  end

  def show
    @meeting = Meeting.find(params[:id])
    @advisee = @meeting.advisee
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])

    if Meeting.update_from_duration(@meeting, meeting_params)
      flash[:success] = 'Meeting updated!'
      redirect_to meeting_path(@meeting)
    else
      flash[:error] = 'There were problems updating that meeting'
      @errors = @meeting.errors.full_messages
      render 'meetings/edit'
    end
  end

  def destroy
    Meeting.destroy(params[:id])

    flash[:success] = 'Meeting deleted!'

    redirect_to advisees_path
  end
end

app/views/meetings/_delete_modal.html.erb
<div id="delete-meeting-modal" class="modal">
  <div class="modal-content">
    <h4>Delete Meeting?</h4>
    <p>
      Are you sure you want to delete this meeting and all associated notes?
    </p>
    <p>
      <b>Warning:</b> This cannot be undone.
    </p>
  </div>
  <div class="modal-footer">
    <%= button_to 'Yes, Delete Meeting',
                  meeting_path(meeting),
                  method: 'delete',
                  class: 'btn danger modal-action modal-close' %>
    <a href="#!" class="modal-action modal-close waves-effect waves-light btn-flat">
      Cancel
    </a>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class="container">
  <h2>Edit Meeting</h2>

  <%= render partial: 'layouts/errors' %>

  <div class="row">
    <div class="col s12">
      <%= form_for @meeting do |f| %>
        <div class="input-field">
          <%= f.text_field :description %>
          <%= f.label :description, class: 'active' %>
        </div>

        <% if @meeting.start_time %>
          <div id="edit-meeting-start-time-data"
               data-start="<%= @meeting.start_time.to_datetime.to_s %>" />
        <% else %>
          <div id="edit-meeting-start-time-data"
               data-start="" />
        <% end %>

        <div class="input-field" id='edit-meeting-start-time'>
          <%= f.text_field :start_time %>
          <%= f.label :start_time, 'Start Time', class: 'active' %>
        </div>

        <div class="input-field">
          <%= f.number_field :duration, step: 5 %>
          <%= f.label :duration, 'Duration', class: 'active' %>
        </div>

        <div class="input-field">
          <%= f.submit 'Save Meeting', class: 'btn primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="container meeting-details">
  <div id="meeting-data"
       data-id="<%= @meeting.id  %>"
       data-description="<%= @meeting.description %>"
       data-advisee-id="<%= @meeting.advisee_id %>"
       data-start="<%= @meeting.start_time.to_datetime.to_s %>"
       data-end="<%= @meeting.end_time.to_datetime.to_s %>" />

  <div id="export-meeting-options">
  </div>
  
  <h1>Meeting</h1>
  <div class="row">
    <div class="col s12">
      <h4>
        <div id="meeting-time">
          <%= @meeting.formatted_time %>
        </div>
      </h4>


    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <%= link_to meeting_meeting_summaries_path(@meeting),
                  method: 'post',
                  class: 'btn primary' do %>
        <i class="material-icons left">email</i>
        Email Summary
      <% end %>

      <%= link_to edit_meeting_path(@meeting), class: 'btn primary' do %>
        <i class="material-icons left">mode_edit</i>
        Edit Meeting
      <% end %>

      <button data-target="delete-meeting-modal" class="btn danger modal-trigger">
        <i class="material-icons left">delete</i>
        Delete Meeting
      </button>
      <%= render partial: 'meetings/delete_modal', locals: { meeting: @meeting } %>
    </div>
  </div>

  <h3>Meeting with:</h3>
  <%= render partial: 'advisees/details' %>

  <% if @meeting.description %>
    <h5><%= @meeting.description %></h5>
  <% end %>

  <div id="meeting-notes">
  </div>
</div>