config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'advisees#index', as: :authenticated_root
  end

  root 'home#index'

  get "/auth/:provider/callback" => 'identities#create'

  resources :advisees do
    resources :graduation_plans, only: [:index, :new, :create]
  end

  resources :graduation_plans, only: [:show, :destroy]

  resources :meetings, only: [:show, :edit, :update, :destroy] do
    resources :meeting_summaries, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :all_meetings, only: [:index]
      resources :google_calendars, only: [:index]
      resources :microsoft_calendars, only: [:index]
      resources :notes, only: [:update, :destroy]
      resources :search_advisees, only: [:index]
      resources :upcoming_meetings, only: [:index]
      resources :courses, only: [:update, :destroy]

      resources :advisees, only: [] do
        resources :advisee_notes, only: [:index, :create]
        resources :meetings, only: [:index, :create]
      end

      resources :meetings, only: [:update, :destroy] do
        resources :meeting_notes, only: [:index, :create]
        resources :google_calendars, only: [:create]
        resources :microsoft_calendars, only: [:create]
      end

      resources :graduation_plans, only: [:update] do
        resources :semesters, only: [:index]
      end

      resources :semesters, only: [] do
        resources :courses, only: [:create]
      end
    end
  end
end

app/models/graduation_plan.rb
class GraduationPlan < ActiveRecord::Base
  belongs_to :advisee
  has_many :semesters, dependent: :destroy

  validates :name, presence: true
  validates :advisee, presence: true

  def create_default_semesters
    years = 4

    final_semester = advisee.graduation_semester
    final_year = advisee.graduation_year

    beginning_semester = get_first_semester(final_semester)
    beginning_year = final_year.to_i - years

    semesters.create!(semester: 'Remaining', year: 1991, remaining_courses: true)

    years.times do |num|
      semesters.create!(semester: 'Fall', year: beginning_year + num)
      semesters.create!(semester: 'Spring', year: beginning_year + num + 1)
      semesters.create!(semester: 'Summer', year: beginning_year + num + 1)

      if num == 3 && final_semester == 'Fall'
        semesters.create!(semester: 'Fall', year: beginning_year + num + 1)
      end
    end

    semesters.order(:year)
  end

  private

  def get_first_semester(final_semester)
    final_semester_index = Semesters.all.find_index(final_semester)
    Semesters.all[final_semester_index - 1]
  end
end

app/controllers/api/v1/graduation_plans_controller.rb
class Api::V1::GraduationPlansController < ApiController
  before_filter :authenticate_user!
  before_filter only: [:update] do
    check_permissions(GraduationPlan.find(params[:id]).advisee)
  end

  def update
    graduation_plan = GraduationPlan.find(params[:id])
    graduation_plan.name = params[:graduation_plan][:name]

    if graduation_plan.save
      render json: {
        message: 'Plan name updated!',
        graduation_plan: graduation_plan
      }
    else
      errors = graduation_plan.errors.full_messages
      render json: {
        message: 'There was a problem updating the graduation plan name',
        errors: errors
      }, status: :bad_request
    end
  end
end

app/controllers/graduation_plans_controller.rb
class GraduationPlansController < ApplicationController
  before_filter :authenticate_user!
  before_filter only: [:index] do
    check_permissions(Advisee.find(params[:advisee_id]))
  end
  before_filter only: [:show, :destroy] do
    check_permissions(GraduationPlan.find(params[:id]).advisee)
  end

  def index
    @advisee = Advisee.find(params[:advisee_id])
    @graduation_plans = @advisee.graduation_plans
  end

  def show
    @graduation_plan = GraduationPlan.find(params[:id])
    @advisee = @graduation_plan.advisee
  end

  def new
    @advisee = Advisee.find(params[:advisee_id])
    @graduation_plan = GraduationPlan.new
  end

  def create
    @advisee = Advisee.find(params[:advisee_id])
    @graduation_plan = @advisee.graduation_plans.new(grad_plan_params)

    if @graduation_plan.save
      @graduation_plan.create_default_semesters

      flash[:success] = 'Graduation plan created!'
      redirect_to graduation_plan_path(@graduation_plan)
    else
      flash[:error] = 'There was a problem with that graduation plan'
      @errors = @graduation_plan.errors.full_messages
      render 'graduation_plans/new'
    end
  end

  def destroy
    graduation_plan = GraduationPlan.find(params[:id])
    advisee = graduation_plan.advisee

    graduation_plan.destroy

    flash[:success] = 'Graduation plan deleted!'
    redirect_to advisee_graduation_plans_path(advisee)
  end

  private

  def grad_plan_params
    params.require(:graduation_plan).permit(:name)
  end
end

app/views/graduation_plans/_delete_modal.html.erb
<div id="delete-plan-modal-<%= graduation_plan.id %>" class="modal">
  <div class="modal-content">
    <h4>Delete Advisee?</h4>
    <p>
      Are you sure you want to delete the graduation plan
      named "<%= graduation_plan.name %>?
    </p>
    <p>
      <b>Warning:</b> This cannot be undone.
    </p>
  </div>
  <div class="modal-footer">
    <%= button_to 'Yes, Delete Plan',
                  graduation_plan_path(graduation_plan),
                  id: "delete-plan-#{graduation_plan.id}",
                  method: 'delete',
                  class: 'btn danger modal-action modal-close' %>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">
      Cancel
    </a>
  </div>
</div>

app/views/graduation_plans/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <%= render 'layouts/errors' %>
    </div>
  </div>

  <%= form_for [@advisee, @graduation_plan] do |f| %>
    <div class="row">
      <div class="col s12 m8 offset-m2">
        <div class="input-field">
          <%= f.text_field :name %>
          <%= f.label :name, class: 'active' %>
        </div>

        <div class="input-field">
          <%= f.submit 'Save Graduation Plan', class: 'btn standard' %>
        </div>
      </div>
    </div>

    <div class="row center">
      <div class="col s12 m6">

      </div>
    </div>
  <% end %>

</div>

app/views/graduation_plans/index.html.erb
<div class="container">
  <h1>Graduation Plans</h1>

  <h3>Plans for:</h3>
  <%= render partial: 'advisees/details' %>

  <div class="center">
    <%= link_to new_advisee_graduation_plan_path(@advisee),
                class: 'btn standard' do %>
      <i class="material-icons left">add</i>
      Add Graduation Plan
    <% end %>
  </div>


  <div class="graduation-plans">
    <% if @graduation_plans.empty? %>
      <div class="center">
        <h5>
          There are no graduation plans for this advisee.
        </h5>
      </div>
    <% end %>

    <div class="row">
      <% @graduation_plans.each do |graduation_plan| %>
        <%= render partial: 'graduation_plans/delete_modal',
                   locals: { graduation_plan: graduation_plan } %>
        <div class="col s12 m4">
          <%= link_to graduation_plan_path(graduation_plan) do %>
            <div class="card blue-grey darken-1">
              <div class="card-content white-text">
                <span class="card-title"><%= graduation_plan.name %></span>
                <p>
                  Last Updated: <br>
                  <%= graduation_plan.updated_at.strftime('%B %d, %Y') %>
                </p>
                <div className="card-action">
                  <button data-target="delete-plan-modal-<%= graduation_plan.id %>"
                          class="delete-plan btn-floating danger modal-trigger">
                    <i class="material-icons">delete</i>
                  </button>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/graduation_plans/new.html.erb
<div class="container">
  <h2>Create a New Graduation Plan</h2>

  <%= render 'graduation_plans/form' %>
</div>

app/views/graduation_plans/show.html.erb
<%= render partial: 'graduation_plans/delete_modal',
           locals: { graduation_plan: @graduation_plan} %>

<div id="graduation-plan-data"
     data-id="<%= @graduation_plan.id %>"
     data-name="<%= @graduation_plan.name %>" />

<div class="row advisee-info">
  <div class="col s12">
    <h5 class="advisee-name">
      Graduation Plan for:
      <%= link_to @advisee.full_name, advisee_path(@advisee) %>
    </h5>
  </div>
</div>

<div id="graduation-plan">
</div>