config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'advisees#index', as: :authenticated_root
  end

  root 'home#index'

  get "/auth/:provider/callback" => 'identities#create'

  resources :advisees do
    resources :graduation_plans, only: [:index, :new, :create]
  end

  resources :graduation_plans, only: [:show, :destroy]

  resources :meetings, only: [:show, :edit, :update, :destroy] do
    resources :meeting_summaries, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :all_meetings, only: [:index]
      resources :google_calendars, only: [:index]
      resources :microsoft_calendars, only: [:index]
      resources :notes, only: [:update, :destroy]
      resources :search_advisees, only: [:index]
      resources :upcoming_meetings, only: [:index]
      resources :courses, only: [:update, :destroy]

      resources :advisees, only: [] do
        resources :advisee_notes, only: [:index, :create]
        resources :meetings, only: [:index, :create]
      end

      resources :meetings, only: [:update, :destroy] do
        resources :meeting_notes, only: [:index, :create]
        resources :google_calendars, only: [:create]
        resources :microsoft_calendars, only: [:create]
      end

      resources :graduation_plans, only: [:update] do
        resources :semesters, only: [:index]
      end

      resources :semesters, only: [] do
        resources :courses, only: [:create]
      end
    end
  end
end

app/views/layouts/_errors.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <% type = 'success' if type == 'notice' %>
  <% type = 'error' if type == 'alert' %> 
  <div class="flash flash-<%= type %>"
       data-type="<%= type %>"
       data-message="<%= message %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_identities_links.html.erb
<li>
  <%= link_to 'Edit Account Info',
      edit_user_registration_path,
      class: 'nav-option' %>
</li>
<li>
  <% if !current_user.identities.where(provider: 'google_oauth2').empty? %>
    <a href="#" class="nav-option">
      Google Account linked!
    </a>
  <% else %>
    <%= link_to 'Link Google Account',
                '/auth/google_oauth2',
                class: 'nav-option' %>
  <% end %>
</li>
<li>
  <% if !current_user.identities.where(provider: 'microsoft_office365').empty? %>
    <a href="#" class="nav-option">
      Microsoft Account linked!
    </a>
  <% else %>
    <%= link_to 'Link Microsoft Account',
                '/auth/microsoft_office365',
                class: 'nav-option' %>
  <% end %>
</li>

app/views/layouts/_identities_links_dropdown.html.erb
<% if current_user %>
  <ul id="user_dropdown" class="dropdown-content">
    <%= render partial: 'layouts/identities_links' %>
  </ul>
<% end %>

app/views/layouts/_mobile_nav_links.html.erb
<% if current_user %>
  <li><%= link_to 'Advisees', advisees_path %></li>
  <li>
     <%= link_to current_user.email,
                 edit_user_registration_path,
                 class: 'nav-option' %>
  </li>
  <li>
    <%= link_to "Sign Out",
                destroy_user_session_path,
                method: :delete,
                class: 'waves-effect waves-light btn danger' %>
  </li>
  <%= render partial: 'layouts/identities_links' %>
<% else %>
  <li>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn primary' %>
  </li>
  <li>
    <%= link_to "Sign In", new_user_session_path, class: 'btn primary' %>
  </li>
<% end %>

app/views/layouts/_nav.html.erb
<%= render partial: 'layouts/identities_links_dropdown' %>

<nav>
  <div class="nav-wrapper">
    <ul>
      <li><a href="/" class="brand-logo">Advising Assistant</a></li>
    </ul>

    <a href="#" data-activates="mobile-nav" class="button-collapse">
      <i class="material-icons">menu</i>
    </a>

    <ul class="right hide-on-med-and-down" id="nav-links">
      <%= render partial: 'layouts/nav_links' %>
    </ul>
    <ul class="side-nav" id="mobile-nav">
      <%= render partial: 'layouts/mobile_nav_links' %>
    </ul>
  </div>
 </nav>

app/views/layouts/_nav_links.html.erb
<% if current_user %>
  <li><%= link_to 'Advisees', advisees_path %></li>
  <li>
    <a class="dropdown-button"
       href="#!"
       data-activates="user_dropdown">
       <%= current_user.email %>
     </a>
  </li>
  <li>
    <%= link_to "Sign Out",
                destroy_user_session_path,
                method: :delete,
                class: 'waves-effect waves-light btn danger' %>
  </li>
<% else %>
  <li>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn primary' %>
  </li>
  <li>
    <%= link_to "Sign In", new_user_session_path, class: 'btn primary' %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Advising Assistant</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  <%= render 'layouts/nav' %>

  <%= render 'layouts/flash' %>

  <%= yield %>

</body>
</html>